export const dbTables = {
  clients: "irpf_clients",
  users: "irpf_users",
  userClientAssignments: "irpf_user_client_assignments",
  expedientes: "irpf_expedientes",
  documents: "irpf_documents",
  extractions: "irpf_extractions",
  operations: "irpf_operations",
  declarationProfiles: "irpf_declaration_profiles",
  assetRegistry: "irpf_asset_registry",
  assetAccounts: "irpf_asset_accounts",
  assetSecurities: "irpf_asset_securities",
  assetCollectiveInvestments: "irpf_asset_collective_investments",
  assetInsurances: "irpf_asset_insurances",
  assetRealEstate: "irpf_asset_real_estate",
  assetMovableGoods: "irpf_asset_movable_goods",
  assetFiscalEvents: "irpf_asset_fiscal_events",
  fiscalAdjustments: "irpf_fiscal_adjustments",
  lots: "irpf_lots",
  saleAllocations: "irpf_sale_allocations",
  alerts: "irpf_alerts",
  exports: "irpf_exports",
  auditLog: "irpf_audit_log"
} as const;
